site_name: SV06 Knowledge Base
site_description: Guides, troubleshooting, upgrades, spare and replacement parts list
site_url: https://sv06.blakadder.com
repo_url: https://github.com/blakadder/sv06
edit_uri: edit/main/docs/

theme:
  name: material
  custom_dir: overrides
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: cyan
      accent: light blue
      toggle:
        icon: material/weather-night
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: cyan
      accent: light blue
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
  font:
    text: Maven Pro
  favicon: images/logo.png
  features:
    - navigation.footer
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.indexes 
    - toc.follow
    - navigation.top
    - content.action.edit
    - toc.follow
  icon:
    admonition:
      tip: material/shopping-outline  
  logo: images/logo.png

nav:
  - Knowledge Base:
    - index.md
    - First Steps with a New SV06: first-steps.md
    - Slicer Configurations: slicers.md
    - Guides: guides.md
    - Common Issues: common-issues.md
    - Troubleshooting: troubleshooting.md
    - Firmware: firmware.md
    - Contact Me: contact.md
  - Parts:
    - Electronics: Parts/electronic-parts.md
    - Extruder: Parts/extruder-parts.md
    - Hot End: Parts/hotend-parts.md
    - Mechanical: Parts/mechanical-parts.md
    - Power Supply: Parts/printable-parts.md
    - Printable: Parts/printable-parts.md
    - Print Bed: Parts/print-bed-parts.md
  - Upgrades:
    - Nozzle: Upgrades/nozzle-upgrades.md
    - Cooling: Upgrades/cooling-upgrades.md
    - Extruder: Upgrades/extruder-upgrades.md
    - Nozzle Light: Upgrades/nozzle-led.md
    - Printable: Upgrades/printed-mods.md
    - Silicone Bed Spacers: Upgrades/silicone-mod.md
  - SV06 Plus:
    - Parts List: Plus/parts-plus.md
    - Pritnable Parts: Plus/printable-parts-plus.md
    - Upgrades: Plus/upgrades-plus.md
    - Firmware: Plus/firmware-plus.md


plugins:
  - search
  - tags
  - social:
      cards_layout_options:
        background_color: "#5F9EA0"
        font_family: Roboto

markdown_extensions:
  - attr_list
  - md_in_html
  # - glightbox
  - tables
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - footnotes
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.snippets:
      auto_append:
        - includes/abbreviations.md
  - toc:
      permalink: true

extra:
  social:
    - icon: fontawesome/brands/twitter 
      link: https://twitter.com/blakadder_
    - icon: fontawesome/brands/instagram
      link: https://instagram.com/blak_adder
    - icon: fontawesome/solid/blog
      link: https://blakadder.com
  
  consent:
    title: Cookie consent
    description: >- 
      We use cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of our documentation and whether users
      find what they're searching for. With your consent, you're helping us to
      make our documentation better.
  analytics:
    provider: google
    property: G-YC1VX2GGRS

copyright: >
  Copyright &copy; 2023 Smart Home News doo –
  <a href="#__consent">cookie settings</a> 
  | <small>Some of the links are affiliate links. If you buy using them I receive a small commission which helps to maintain this site.</small>
